#!/usr/bin/env python3

import usb.core

IN_REQUEST  = usb.ENDPOINT_IN  | usb.RECIP_DEVICE | usb.TYPE_VENDOR
OUT_REQUEST = usb.ENDPOINT_OUT | usb.RECIP_DEVICE | usb.TYPE_VENDOR

VENDOR_REQUEST_JTAG_CLEAR_OUT_BUFFER = 0xb0
VENDOR_REQUEST_JTAG_SET_OUT_BUFFER   = 0xb1
VENDOR_REQUEST_JTAG_GET_IN_BUFFER    = 0xb2
VENDOR_REQUEST_JTAG_SCAN             = 0xb3
VENDOR_REQUEST_JTAG_RUN_CLOCK        = 0xb4

d = usb.core.find(idVendor=0x1d50, idProduct=0x60e7)

# reset
d.ctrl_transfer(OUT_REQUEST, VENDOR_REQUEST_JTAG_RUN_CLOCK, 5, 1)

# move to shift-DR
d.ctrl_transfer(OUT_REQUEST, VENDOR_REQUEST_JTAG_RUN_CLOCK, 1, 0)
d.ctrl_transfer(OUT_REQUEST, VENDOR_REQUEST_JTAG_RUN_CLOCK, 1, 1)
d.ctrl_transfer(OUT_REQUEST, VENDOR_REQUEST_JTAG_RUN_CLOCK, 1, 0)
d.ctrl_transfer(OUT_REQUEST, VENDOR_REQUEST_JTAG_RUN_CLOCK, 1, 0)

# shift 32 bits
#d.ctrl_transfer(OUT_REQUEST, VENDOR_REQUEST_JTAG_CLEAR_OUT_BUFFER)
d.ctrl_transfer(OUT_REQUEST, VENDOR_REQUEST_JTAG_SET_OUT_BUFFER)
d.ctrl_transfer(OUT_REQUEST, VENDOR_REQUEST_JTAG_SCAN, 32)
print(bytes(d.ctrl_transfer(IN_REQUEST, VENDOR_REQUEST_JTAG_GET_IN_BUFFER, data_or_wLength=4)))
